import type { Metadata } from "next";
import { Roboto } from 'next/font/google';

import "./globals.css";
import { Header } from "./components/header/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
          <Header />
          {children}
      </body>
    </html>
  );
}
